### ISSUE TITLE
minFontSize and MaxFontSize don't work

### ISSUE THREAD

**Issue by RhysyG** [Protoss78/textfit-div#5]
Hi there,

I tried setting the minFontSize and MaxFontSize but it doesn't affect the element.

![screen shot 2017-05-05 at 3 30 15 pm](https://cloud.githubusercontent.com/assets/5491092/25734576/e2fb83a4-31a7-11e7-92fa-e73089863d99.png)

Thanks.

**Comment by Protoss78** [comment]
Try changing minfontsize="16" and maxfontsize="20" to min-font-size="16" and max-font-size="20". That should solve the problem.
This is a standard mechanism in the used Polymer framework and described in more detail here:
https://www.polymer-project.org/1.0/docs/devguide/properties#property-name-mapping

**Comment by Protoss78** [comment]
@RhysyG : Let me know if this change fixes your error or not. :-)

**Comment by RhysyG** [comment]
Yes thank you, this worked and followed the official docs correctly. Sorry, I saw the names listed in the properties and copied them.

**Comment by Protoss78** [comment]
Yep. Happened to me all the time as well. Takes time to get used to. :-)
