### ISSUE TITLE
Can't dismiss "Set a static height and width on the target"

### ISSUE THREAD

**Issue by RhysyG** [Protoss78/textfit-div#6]
Hey!

I can't seem to fix this console warning. I have set a width and height around the textfit-div, ON the textfit-div but it doesn't seem to affect the warning. I can do this fine when playing around in the demo/index.html file, but when using it in my app I get the warning.

Thanks.
![textfit-div](https://cloud.githubusercontent.com/assets/5491092/25790391/797ce976-33fb-11e7-9476-9a14d5b79caa.png)

**Comment by Protoss78** [comment]
I'll look into that issue, when I start upgrading the element to Polymer 2.0 hybrid mode. Maybe I'll start on it this weekend. Fingers crossed.

**Comment by Protoss78** [comment]
Can you retry using the latest textfit-div version 1.0.0
